<a href="https://colab.research.google.com/github/priyansh918/AIML-D--RA2411026030191_DSML-TRAINING/blob/main/RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Predict laptop buying occurence using Random Forest Algorithm::***

In [14]:
#import the necessary liberaries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [15]:
#load and upload the dataset
df=pd.read_csv('/laptop_buying_data.csv',
na_values=[""," ","NA","N/A","null","NULL","none","?"])
df.head()

    Age  Income Student  Credit Score  Location Buys Laptop
0  25.0    High      No         700.0     Urban         Yes
1  30.0    High     Yes         650.0     Urban          No
2  22.0     Low      No         580.0     Rural          No
3  35.0  Medium      No         620.0     Urban         Yes
4  28.0     Low     Yes         690.0  Suburban         Yes

In [16]:
#Draw inspection
#rows and columns
df.shape
#columns
print(df.columns.tolist)
#Dataset infornmation
df.info()
#checking the missing values
df.isnull().sum()
#drop missing rows with missing values
df=df.dropna()
#check again
df.isnull().sum()

<bound method IndexOpsMixin.tolist of Index(['Age', 'Income', 'Student', 'Credit Score', 'Location', 'Buys Laptop'], dtype='object')>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           51 non-null     float64
 1   Income        50 non-null     object
 2   Student       51 non-null     object
 3   Credit Score  50 non-null     float64
 4   Location      51 non-null     object
 5   Buys Laptop   52 non-null     object
dtypes: float64(2), object(4)
memory usage: 2.6+ KB

Age             0
Income          0
Student         0
Credit Score    0
Location        0
Buys Laptop     0
dtype: int64